__title__ = "Ts Sort Out Audit Tool"
__description__ = "Software Tool to audit Transshipment Sort Out Audit process"
__version__ = "0.6"
__author__ = "Cerreta, Lorenzo"
__mail__ = "lcerreta@amazon.it"
